version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src:delegated
      - ./prisma:/app/prisma:delegated
      - ./package.json:/app/package.json:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated
      - ./scripts:/app/scripts:delegated
      - ./tsconfig.scripts.json:/app/tsconfig.scripts.json:delegated
      - ./nodemon.json:/app/nodemon.json:delegated
      - api_node_modules:/app/node_modules
      - api_dist:/app/dist
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MYSQL_DATABASE_URL=mysql://express-boilerplate:express-boilerplate@db:3306/express-boilerplate
      - RUN_SEEDS=true
      - PROMETHEUS_USER=${PROMETHEUS_USER:-admin}
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD:-admin}
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    # command: >
    #   sh -c "
    #     # mkdir -p /app/node_modules/.prisma &&
    #     # npx prisma generate &&
    #     # npx prisma migrate deploy &&
    #     # if [ \"$$RUN_SEEDS\" = \"true\" ]; then npm run seed:dev; fi &&
    #     # npx nodemon
    #   "
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "http://localhost:8080/monitoring/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  api_node_modules:
  api_dist:
